pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/AB-SJSU/CMPE_272_HW_2_Twitter_Service.git'
        NODE_ENV = 'production'
    }

    stages {
        stage('Clone Private Repo') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                    sh 'git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/AB-SJSU/CMPE_272_HW_2_Twitter_Service'
                }
            }
        }
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Archive Build') {
            steps {
                archiveArtifacts artifacts: '.next/**', fingerprint: true
            }
        }
    }

    post {
        success {
            echo '✅ Build succeeded!'
        }
        failure {
            echo '❌ Build failed.'
        }
    }

    stage('List Files') {
            steps {
                sh 'ls -la CMPE_272_HW_2_Twitter_Service'
            }
        }
}

