pipeline {
    agent any

    stages {
        stage('Clone Private Repo') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                    sh 'git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/AB-SJSU/CMPE_272_HW_2_Twitter_Service'
                }
            }
        }
    }
}

